// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsJeSdgbGXua8jsZIZRJTz7o7d3GhqiV4',
    appId: '1:97837753448:web:1b3c77e8ce9f69a88b87dd',
    messagingSenderId: '97837753448',
    projectId: 'attendtify-6c251',
    authDomain: 'attendtify-6c251.firebaseapp.com',
    storageBucket: 'attendtify-6c251.firebasestorage.app',
    measurementId: 'G-3E1X049N91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvV_4IOMgOlCCqM78m6RV8k5e5ZjqEaVs',
    appId: '1:97837753448:android:54f688edd82e8d228b87dd',
    messagingSenderId: '97837753448',
    projectId: 'attendtify-6c251',
    storageBucket: 'attendtify-6c251.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnd55KtJbbJSAgJE_ZgE4NOuDmU8ScKMs',
    appId: '1:97837753448:ios:bd0ebf76e74c010b8b87dd',
    messagingSenderId: '97837753448',
    projectId: 'attendtify-6c251',
    storageBucket: 'attendtify-6c251.firebasestorage.app',
    iosBundleId: 'com.example.attendify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnd55KtJbbJSAgJE_ZgE4NOuDmU8ScKMs',
    appId: '1:97837753448:ios:bd0ebf76e74c010b8b87dd',
    messagingSenderId: '97837753448',
    projectId: 'attendtify-6c251',
    storageBucket: 'attendtify-6c251.firebasestorage.app',
    iosBundleId: 'com.example.attendify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsJeSdgbGXua8jsZIZRJTz7o7d3GhqiV4',
    appId: '1:97837753448:web:870cee470cbdba738b87dd',
    messagingSenderId: '97837753448',
    projectId: 'attendtify-6c251',
    authDomain: 'attendtify-6c251.firebaseapp.com',
    storageBucket: 'attendtify-6c251.firebasestorage.app',
    measurementId: 'G-XJC0V4NFC6',
  );
}
